### ISSUE TITLE
为啥 我用的时候只有点击一次复制 第二次点击就没反应了呢

### ISSUE THREAD

**Issue by Mr-Lsl** [freeshineit/react-clipboardjs-copy#2]
<ReactClipboard target={'#copy-target'}
                             onSuccess={() => this.onCopyResponse()}
                              onError={(e) => console.log(e)}>
                                    <li className={list["className"]}>
                                        <img src={require(`../images/${list["img"]}`)}alt=""/>
                                        <div className="dataAnalysis_right_word">{list["label"]}</div>
                                    </li>
</ReactClipboard>

**Comment by freeshineit** [comment]
你可以代码截取全一点吗？ @Mr-Lsl

**Comment by freeshineit** [comment]
@Mr-Lsl   已经修复了  可以更新到@1.2.1

**Comment by liuyu1** [comment]
你好为什么我使用的时候会报错，


./node_modules/react-clipboardjs-copy/src/Component.js
Module parse failed: Unexpected token (50:79)
You may need an appropriate loader to handle this file type.
|
|     render() {
|         const { target, onSuccess, onError, text, action, selection, children, ...other } = this.props;
|         const elem = React.Children.only(children);
|

这是报错信息，我使用的是最新版本的。有谁遇到过吗？

**Comment by freeshineit** [comment]
@liuyu1  能看一下你 babel 的版本吗

**Comment by liuyu1** [comment]
@freeshineit     这个是我的版本号，
"babel-eslint": "^8.2.2",
    "babel-plugin-array-includes": "^2.0.3",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.7.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",

**Comment by liuyu1** [comment]
@freeshineit 我现在把react-clipboardjs-copy版本恢复到了1.0.3已经可以正常运行了。

**Comment by liuyu1** [comment]
@freeshineit 好的，谢谢，

**Comment by freeshineit** [comment]
@1.3.0 已经解决这个问题
